### PR TITLE
Background mode

### PR DESCRIPTION
**Pull request by lorenzoPrimi**
Some strings needs to be corrected. The app should be tested on a real device for local push notifications and background tests.

### CODE REVIEW

**Comment by lorenzoPrimi** [comment]
@bassosimone can we merge this by tonight?

**Comment by bassosimone** [comment]
I am doing some further tests because I'm not sure whether background mode is not working correctly or I am not testing correctly. So, I am now using the approach that I start a test, I wait a specific number of minutes and then I go on the device to make sure there always is the notification.

Meanwhile, I have reverted my 51017f5 diff because it was making the device slower and, of course, since this was just meant for debugging we can safely ignore it.

- [ ] run 1
- [ ] run 2
- [ ] run 3
- [ ] run 4
- [ ] run 5
- [ ] run 6
- [ ] run 7
- [ ] run 8
- [ ] run 9
- [ ] run 10
- [ ] run 11
- [ ] run 12
- [ ] run 13
- [ ] run 14
- [ ] run 15
- [ ] run 16

**Comment by bassosimone** [comment]
@lorenzoPrimi I don't think we should commit this file: `ooniprobe.xcworkspace/xcuserdata/lorenzo.xcuserdatad/UserInterfaceState.xcuserstate`. Please backup it. I am going to remove it from the pull request and add it to the `.gitignore` file, unless you have some strong objection.

**Comment by lorenzoPrimi** [comment]
It was already in gitignore, but I forgot to modify the .girignore with the new project name

**Comment by bassosimone** [comment]
Merging!

**Pull request merged**
